import type { ProPlayer } from '@/types'

const HLTV  = { color: '#ff8c00', bg: 'rgba(255,140,0,0.08)',   border: 'rgba(255,140,0,0.25)'   }
const FC    = { color: '#ff5500', bg: 'rgba(255,85,0,0.08)',    border: 'rgba(255,85,0,0.25)'    }
const LP    = { color: '#a78bfa', bg: 'rgba(167,139,250,0.08)', border: 'rgba(167,139,250,0.25)' }
const ST    = { color: '#9aa8b2', bg: 'rgba(154,168,178,0.07)', border: 'rgba(154,168,178,0.2)'  }
const TW    = { color: '#1da1f2', bg: 'rgba(29,161,242,0.08)',  border: 'rgba(29,161,242,0.25)'  }
const TCH   = { color: '#7c5cbf', bg: 'rgba(124,92,191,0.08)',  border: 'rgba(124,92,191,0.25)'  }
const L = (label: string, url: string, c: typeof HLTV) => ({ label, url, ...c })

export const CS2_PROS: ProPlayer[] = [
  {
    game:'cs', nickname:'s1mple', fullName:'Aleksandr Kostylev', country:'🇺🇦',
    team:'BC.Game', rating:'1.28', ratingLabel:'HLTV Avg', role:'AWPer',
    accent:'#f5a623', extra:'👑 GOAT CS · #1 HLTV 2018-2021 · Stockholm Major MVP',
    steamId:'76561198034202275',
    photo: undefined,
    links:[
      L('HLTV','https://www.hltv.org/player/7998/s1mple',HLTV),
      L('FACEIT','https://www.faceit.com/en/players/s1mple',FC),
      L('TWITTER','https://x.com/s1mpleO',TW),
      L('TWITCH','https://www.twitch.tv/s1mple',TCH),
      L('LIQUIPEDIA','https://liquipedia.net/counterstrike/S1mple',LP),
      L('STEAM',`https://steamcommunity.com/profiles/76561198034202275`,ST),
    ],
  },
  {
    game:'cs', nickname:'donk', fullName:'Danil Kryshkovets', country:'🇷🇺',
    team:'Team Spirit', rating:'1.37', ratingLabel:'HLTV 2024', role:'Rifler / Entry',
    accent:'#48bb78', extra:'🏆 Shanghai Major 2024 · #1 HLTV 2024 · Best debut in history',
    steamId:'76561199064045520',
    photo: undefined,
    links:[
      L('HLTV','https://www.hltv.org/player/21167/donk',HLTV),
      L('FACEIT','https://www.faceit.com/en/players/donk_1',FC),
      L('TWITTER','https://x.com/donk_1w',TW),
      L('TWITCH','https://www.twitch.tv/donk_1',TCH),
      L('LIQUIPEDIA','https://liquipedia.net/counterstrike/Donk',LP),
      L('STEAM',`https://steamcommunity.com/profiles/76561199064045520`,ST),
    ],
  },
  {
    game:'cs', nickname:'ZywOo', fullName:'Mathieu Herbaut', country:'🇫🇷',
    team:'Team Vitality', rating:'1.35', ratingLabel:'HLTV Avg', role:'AWPer',
    accent:'#ffdd57', extra:'🏆🏆🏆 3× Major · #1 HLTV 4× · 30 MVP Awards (record)',
    steamId:'76561198380899939',
    photo: undefined,
    links:[
      L('HLTV','https://www.hltv.org/player/11893/zywoo',HLTV),
      L('FACEIT','https://www.faceit.com/en/players/ZywOo',FC),
      L('TWITTER','https://x.com/ZywOo',TW),
      L('TWITCH','https://www.twitch.tv/zywoo',TCH),
      L('LIQUIPEDIA','https://liquipedia.net/counterstrike/ZywOo',LP),
      L('STEAM',`https://steamcommunity.com/profiles/76561198380899939`,ST),
    ],
  },
  {
    game:'cs', nickname:'m0NESY', fullName:'Ilya Osipov', country:'🇷🇺',
    team:'Team Falcons', rating:'1.29', ratingLabel:'HLTV Avg', role:'AWPer',
    accent:'#26d07c', extra:'🏆 BLAST World Final 2024 · #2 HLTV 2024 · 4× S-Tier MVP',
    steamId:'76561199063533761',
    photo: undefined,
    links:[
      L('HLTV','https://www.hltv.org/player/21922/m0nesy',HLTV),
      L('FACEIT','https://www.faceit.com/en/players/m0NESY',FC),
      L('TWITTER','https://x.com/m0NESY',TW),
      L('TWITCH','https://www.twitch.tv/m0nesy',TCH),
      L('LIQUIPEDIA','https://liquipedia.net/counterstrike/M0NESY',LP),
      L('STEAM',`https://steamcommunity.com/profiles/76561199063533761`,ST),
    ],
  },
  {
    game:'cs', nickname:'NiKo', fullName:'Nikola Kovač', country:'🇧🇦',
    team:'Team Falcons', rating:'1.24', ratingLabel:'HLTV Avg', role:'Rifler / Entry',
    accent:'#ff6b35', extra:'🏅 9× Top-20 HLTV · Antwerp Major 2022 · GOAT Rifler',
    steamId:'76561198136523281',
    photo: undefined,
    links:[
      L('HLTV','https://www.hltv.org/player/3741/niko',HLTV),
      L('FACEIT','https://www.faceit.com/en/players/NiKo_',FC),
      L('TWITTER','https://x.com/G2NiKo',TW),
      L('TWITCH','https://www.twitch.tv/niko',TCH),
      L('LIQUIPEDIA','https://liquipedia.net/counterstrike/NiKo',LP),
      L('STEAM',`https://steamcommunity.com/profiles/76561198136523281`,ST),
    ],
  },
  {
    game:'cs', nickname:'device', fullName:'Nicolai Reedtz', country:'🇩🇰',
    team:'Astralis', rating:'1.18', ratingLabel:'HLTV Avg', role:'AWPer',
    accent:'#e53e3e', extra:'🏆🏆🏆🏆 4× Major · Astralis Dynasty · #1 HLTV 2× ',
    steamId:'76561197987713664',
    photo: undefined,
    links:[
      L('HLTV','https://www.hltv.org/player/1312/device',HLTV),
      L('FACEIT','https://www.faceit.com/en/players/device',FC),
      L('TWITTER','https://x.com/device',TW),
      L('TWITCH','https://www.twitch.tv/device',TCH),
      L('LIQUIPEDIA','https://liquipedia.net/counterstrike/Device',LP),
      L('STEAM',`https://steamcommunity.com/profiles/76561197987713664`,ST),
    ],
  },
  {
    game:'cs', nickname:'sh1ro', fullName:'Dmitriy Sokolov', country:'🇷🇺',
    team:'Team Spirit', rating:'1.22', ratingLabel:'HLTV Avg', role:'AWPer',
    accent:'#63b3ed', extra:'🏆 Shanghai Major 2024 · #5 HLTV 2025 · Best AWP on Spirit',
    steamId:'76561198334759556',
    photo: undefined,
    links:[
      L('HLTV','https://www.hltv.org/player/18068/sh1ro',HLTV),
      L('FACEIT','https://www.faceit.com/en/players/sh1ro',FC),
      L('TWITTER','https://x.com/sh1ro_cs',TW),
      L('TWITCH','https://www.twitch.tv/sh1ro',TCH),
      L('LIQUIPEDIA','https://liquipedia.net/counterstrike/Sh1ro',LP),
      L('STEAM',`https://steamcommunity.com/profiles/76561198334759556`,ST),
    ],
  },
  {
    game:'cs', nickname:'ropz', fullName:'Robin Kool', country:'🇪🇪',
    team:'Team Vitality', rating:'1.20', ratingLabel:'HLTV Avg', role:'Rifler / Support',
    accent:'#68d391', extra:'🏆🏆 Antwerp+Budapest Major · #3 HLTV 2025',
    steamId:'76561198287487713',
    photo: undefined,
    links:[
      L('HLTV','https://www.hltv.org/player/11816/ropz',HLTV),
      L('FACEIT','https://www.faceit.com/en/players/ropz',FC),
      L('TWITTER','https://x.com/ropzCSGO',TW),
      L('TWITCH','https://www.twitch.tv/ropz',TCH),
      L('LIQUIPEDIA','https://liquipedia.net/counterstrike/Ropz',LP),
      L('STEAM',`https://steamcommunity.com/profiles/76561198287487713`,ST),
    ],
  },
  {
    game:'cs', nickname:'broky', fullName:'Håvard Nygaard', country:'🇱🇻',
    team:'FaZe Clan', rating:'1.19', ratingLabel:'HLTV Avg', role:'AWPer',
    accent:'#9f7aea', extra:'🏆 Antwerp Major 2022 · FaZe Clan AWPer',
    steamId:'76561198354958206',
    photo: undefined,
    links:[
      L('HLTV','https://www.hltv.org/player/15513/broky',HLTV),
      L('FACEIT','https://www.faceit.com/en/players/broky',FC),
      L('TWITTER','https://x.com/broky_cs',TW),
      L('TWITCH','https://www.twitch.tv/broky',TCH),
      L('LIQUIPEDIA','https://liquipedia.net/counterstrike/Broky',LP),
      L('STEAM',`https://steamcommunity.com/profiles/76561198354958206`,ST),
    ],
  },
  {
    game:'cs', nickname:'karrigan', fullName:'Finn Andersen', country:'🇩🇰',
    team:'FaZe Clan', rating:'1.05', ratingLabel:'HLTV Avg', role:'IGL',
    accent:'#9f7aea', extra:'🏆 Antwerp Major 2022 · IGL Hall of Fame · 15+ years at the top',
    steamId:'76561197962898032',
    photo: undefined,
    links:[
      L('HLTV','https://www.hltv.org/player/429/karrigan',HLTV),
      L('FACEIT','https://www.faceit.com/en/players/karrigan',FC),
      L('TWITTER','https://x.com/karriganCSGO',TW),
      L('TWITCH','https://www.twitch.tv/karrigan',TCH),
      L('LIQUIPEDIA','https://liquipedia.net/counterstrike/Karrigan',LP),
      L('STEAM',`https://steamcommunity.com/profiles/76561197962898032`,ST),
    ],
  },
  {
    game:'cs', nickname:'Twistzz', fullName:'Russel Van Dulken', country:'🇨🇦',
    team:'FaZe Clan', rating:'1.18', ratingLabel:'HLTV Avg', role:'Rifler / Entry',
    accent:'#9f7aea', extra:'🏆 Antwerp Major 2022 · Best NA player of the generation',
    steamId:'76561198137689512',
    photo: undefined,
    links:[
      L('HLTV','https://www.hltv.org/player/10394/twistzz',HLTV),
      L('FACEIT','https://www.faceit.com/en/players/Twistzz',FC),
      L('TWITTER','https://x.com/Twistzz',TW),
      L('TWITCH','https://www.twitch.tv/twistzz',TCH),
      L('LIQUIPEDIA','https://liquipedia.net/counterstrike/Twistzz',LP),
      L('STEAM',`https://steamcommunity.com/profiles/76561198137689512`,ST),
    ],
  },
  {
    game:'cs', nickname:'electronic', fullName:'Denis Sharipov', country:'🇷🇺',
    team:'Natus Vincere', rating:'1.15', ratingLabel:'HLTV Avg', role:'Rifler / Lurker',
    accent:'#f5a623', extra:'🏆 Stockholm Major 2021 · NaVi legend',
    steamId:'76561198044045107',
    photo: undefined,
    links:[
      L('HLTV','https://www.hltv.org/player/8918/electronic',HLTV),
      L('FACEIT','https://www.faceit.com/en/players/electronic',FC),
      L('TWITTER','https://x.com/electronic_csgO',TW),
      L('TWITCH','https://www.twitch.tv/electronic',TCH),
      L('LIQUIPEDIA','https://liquipedia.net/counterstrike/Electronic',LP),
      L('STEAM',`https://steamcommunity.com/profiles/76561198044045107`,ST),
    ],
  },
]
